services:
  skylight:
    image: colinstubbs/sunlight:latest
    entrypoint: ["/usr/local/bin/skylight-entrypoint.sh"]
    working_dir: /skylight
    restart: unless-stopped
    environment:
      # Optional: Timezone
      #- TZ=${TZ:-UTC}
      # Debug mode, set to true to enable more verbose output from the entrypoint script.
      #- DEBUG=${DEBUG:-}
      # set to true to load test certs from testdata/
      # Skylight configuration, refer to skylight-entrypoint.sh
      - SKYLIGHT_LISTEN_ADDRESS=${SKYLIGHT_LISTEN_ADDRESS:-0.0.0.0}
      # if you don't provide an ACME config or use a test cert via -testcert/skylight-key.pem/skylight.pem then skylight will actually listen on plain HTTP, not HTTPS.
      - SKYLIGHT_LISTEN_PORT=${SKYLIGHT_LISTEN_PORT:-80}
      - SUNLIGHT_LOG_NAME=${SUNLIGHT_LOG_NAME:-testlog}
      # NOTE: same thing with skylight, host header will need to match. If you use localhost here even 127.0.0.1 will not work.
      - SUNLIGHT_MONITORING_PREFIX=${SUNLIGHT_MONITORING_PREFIX:-http://localhost}
      - SKYLIGHT_TESTCERT=${SKYLIGHT_TESTCERT:-false}
    ports:
      - "80:80"
    volumes:
      - ctlog_data:/tank/logs/${SUNLIGHT_LOG_NAME:-testlog}/data
    healthcheck:
      test: curl --silent --fail https://localhost:${SKYLIGHT_LISTEN_PORT:-80}/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s