
services:
  caddy:
    build:
      context: ./example/caddy/
    image: colinstubbs/caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ctlog_data:/usr/share/caddy
      - ./example/caddy/Caddyfile:/etc/caddy/Caddyfile
      # persistent logs if desired
      #- logs:/var/log/caddy
